### ISSUE TITLE
Make sure the plugin considers remote galleys

### ISSUE THREAD

**Issue by jmacgreg** [jmacgreg/portico#10]
Remote galley is currently broken, resulting in the following fatal error: 

PHP Fatal error:  Uncaught Error: Call to a member function getLocalizedName() on null in .../plugins/importexport/portico/PorticoExportDom.inc.php:158

The plugin needs to at least fail gracefully on this, or (optimally) include the remote file.

**Comment by jonasraoni** [comment]
Hi @jmacgreg!
I've added other small fixes to the PR, please check if it's ok to include the affiliation for all the authors (I've removed the `if ($authorIndex == 0)`) or if this option should be included as a setting.
