### ISSUE TITLE
Clean up zip files on journal server post-FTP

### ISSUE THREAD

**Issue by jmacgreg** [jmacgreg/portico#5]
Zip files are created on the journal as part of the export or FTP batch send process. These need to be cleaned up after the export or FTP is complete.

**Comment by LiamNorman** [comment]
Hey @jmacgreg, I can tackle this one. Would you want all zip files to be removed after exporting issues via FTP or just the last zip file that was created?

**Comment by LiamNorman** [comment]
Also would you be able to label this issue hacktoberfest?  👍

**Comment by jmacgreg** [comment]
Hi LiamNorman, sure and sure! Thanks for offering! I think the function should just remove the zip file that was created during that particular runthrough, so the latter. If you have any questions, just let me know.

**Comment by LiamNorman** [comment]
Hey @jmacgreg, I've made the change! Let me know what you think? I also fixed the FTP connection which wasn't being closed properly in this case. So now after a file is uploaded via FTP either one by one or in bulk then the zip file is deleted from the root directory. 👍  Let me know if you want any changes or have any questions?
