### ISSUE TITLE
Compatibility with OJS 3.1.2

### ISSUE THREAD

**Issue by arleysoto** [jmacgreg/portico#8]
We have recently updated an OJS to 3.1.2.0, but we have not been able to install Portico plugin through the UI using the admin user.

After uploading the tar.gz file, it prompts the warning "plugin already installed..." but actually, it doesn't show it in the plugin list.

**Comment by jmacgreg** [comment]
Hi Arley, when you load the Plugin page, do you get any errors in your error log?

**Comment by arleysoto** [comment]
Yes, I got these errors in the log:

![image](https://user-images.githubusercontent.com/48956524/57146070-18c52b00-6d8a-11e9-9bcf-ac814da02846.png)

And these warnings in the UI:

1st:
![image](https://user-images.githubusercontent.com/48956524/57146210-6b064c00-6d8a-11e9-811e-fe1e0a6fd3d1.png)

2nd:
![image](https://user-images.githubusercontent.com/48956524/57146232-778aa480-6d8a-11e9-8ffd-6ef9a7bd9588.png)

**Comment by wesambhaya** [comment]
The Portico Plugin has not been upgraded for since 3.1.2 and it will not work with the current version.

**Comment by jmacgreg** [comment]
Hi all - the most recent version (v 3.1, available at https://github.com/jmacgreg/portico/tags) will work with OJS 3.1.2.
